# Generated by Django 2.2.dev20180521165340 on 2018-05-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('logo', models.ImageField(default='img/None/no-img.jpg', upload_to='img/')),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(default='img/None/no-img.jpg', upload_to='img/'),
        ),
    ]
