# Generated by Django 2.2.dev20180521165340 on 2018-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_auto_20180523_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='entrenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apodo', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('rut', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='juego',
            new_name='equipo',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='estatura',
            field=models.FloatField(),
        ),
    ]
